apiVersion: v1
kind: Service
metadata:
  name: registerservice-service
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: registerservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registerservice-deployment
  labels:
    app: registerservice
    platform: aks
    environment: dev
    release: cassiopeia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registerservice
  template:
    metadata:
      labels:
        app: registerservice
    spec:
      containers:
        - name: registerservice
          image: ghcr.io/jacqinthebox/escaperooms/registerservice:1.0.52
          env:
            - name: DB_SERVER
              value: sqledge-service
            - name: DB_NAME
              value: FLOEPS
            - name: DB_PASSWORD
              value: 123Tralala^
            - name: DB_USERNAME
              value: sa
            - name: APP_SECRET_KEY
              value: SomeNiceSecretKey
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
    platform: aks
    environment: dev
    release: cassiopeia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/jacqinthebox/escaperooms/frontend:1.0.52
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: frontend-configmap
              mountPath: /usr/share/app/.env
              subPath: .env
      volumes:
        - name: frontend-configmap
          configMap:
            name: frontend-configmap
---
apiVersion: v1
data:
  .env: |
    API_URL=http://0.0.0.0:5000
    NOTE_FROM_FRONTEND_SERVICE=just_for_demo
kind: ConfigMap
metadata:
  name: frontend-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: sqledge-service
spec:
  selector:
    app: sqledge
  ports:
    - protocol: TCP
      port: 1433
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqledge-statefulset
spec:
  serviceName: sqledge-service
  replicas: 1
  selector:
    matchLabels:
      app: sqledge
  template:
    metadata:
      labels:
        app: sqledge
    spec:
      containers:
        - name: sqledge
          image: mcr.microsoft.com/azure-sql-edge
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqledge-sa-secret
                  key: secret