apiVersion: v1
kind: Service
metadata:
  name: register-service-service
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: register-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-service-deployment
  labels:
    app: register-service
    platform: aks
    environment: dev
    release: cassiopeia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register-service
  template:
    metadata:
      labels:
        app: register-service
    spec:
      containers:
        - name: register-service
          image: ghcr.io/jacqinthebox/escaperooms/registerservice:latest
          env:
            - name: DB_SERVER
              value: sqledge
            - name: DB_NAME
              value: FLOEPS
            - name: DB_PASSWORD
              value: 123Tralala^
            - name: DB_USERNAME
              value: sa
            - name: APP_SECRET_KEY
              value: SomeNiceSecretKey
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: register-service-volume
              mountPath: /app
      volumes:
        - name: register-service-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
    platform: aks
    environment: dev
    release: cassiopeia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/jacqinthebox/escaperooms/frontend:1.0.27
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: frontend-configmap
              mountPath: /usr/share/app/.env
              subPath: .env
      volumes:
        - name: frontend-configmap
          configMap:
            name: frontend-configmap