apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: teampubsub
spec:
  metadata:
  - name: redisHost
    value: redis-service:6379
  - name: redisPassword
    value: ""
  type: pubsub.redis
  version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
