apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scoreservice-scaler
  labels:
    app: scoreservice
    name: scoreservice
spec:
  scaleTargetRef:
    cooldownPeriod: 20
    maxReplicaCount: 5
    minReplicaCount: 0
    pollingInterval: 5
    name: scoreservice-deployment
    kind: Deployment
  minReplicaCount: 0
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: imagequeue
      queueLength: '1'
    authenticationRef:
      name: trigger-auth-servicebus
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-servicebus
spec:
  secretTargetRef:
  - parameter: connection
    name: servicebus-connectionstring-secret
    key: secret