apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  labels:
    release: {{ .Release.Name }}-mssql
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433

