name: Roomservice Container CD

on:
  push:
    paths:
      - src/roomservice/*
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      - name: Get next semver tag
        id: next_tag
        uses: dotnet/nbgv@master
        with:
          setAllVars: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push container image
        uses: docker/build-push-action@v3
        with:
          context: src/roomservice
          registry: ghcr.io
          repository: jacqinthebox/escaperooms
          push: true
          tags: | 
            ghcr.io/${{ github.repository_owner }}/escaperooms/roomservice:${{ steps.next_tag.outputs.SimpleVersion }}
            ghcr.io/${{ github.repository_owner }}/escaperooms/roomservice:${{ steps.next_tag.outputs.GitCommitId }}
            ghcr.io/${{ github.repository_owner }}/escaperooms/roomservice:latest
