name: Frontend Container CI

on:
  push:
#    paths:
#      - src/frontend/*
#    branches:
#      except:
#        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          cd src/frontend
          docker build -t ghcr.io/jacqinthebox/escaperooms/frontend:latest .
