name: Helm chart release yes

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-helm@v2
        with:
          version: 3.4.1
      - run: helm package .
      - run: |
          echo "${{ secrets.GH_PAT }}" | docker login docker.pkg.github.com -u "${{ secrets.GH_USERNAME }}" --password-stdin
          docker build -t docker.pkg.github.com/${{ secrets.REPO_OWNER }}/${{ secrets.REPO_NAME }}:${{ github.sha }} .
          docker push docker.pkg.github.com/${{ secrets.REPO_OWNER }}/${{ secrets.REPO_NAME }}:${{ github.sha }}
