name: Push helm chart to ghcr
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to ghcr
        run: docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GH_TOKEN }}
      - name: Package chart
        run: helm package deploy/helm/frontend --version=latest
      - name: Push chart to ghcr
        run: helm push frontend-latest.tgz ghcr.io/${{ github.repository_owner }}/escaperooms
